/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const Comment = IDL.Record({
  'id' : CommentId,
  'authorVerified' : IDL.Bool,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'postId' : PostId,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const NewsPost = IDL.Record({
  'id' : PostId,
  'authorVerified' : IDL.Bool,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'shares' : IDL.Nat,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
  'commentsCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'author' : IDL.Null,
  'contentCreator' : IDL.Null,
  'commonUser' : IDL.Null,
  'groupHead' : IDL.Null,
  'subscriber' : IDL.Null,
  'administrator' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'verified' : IDL.Bool,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : UserRole,
  'savedPosts' : IDL.Vec(PostId),
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
});
export const UserProfileInput = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [NewsPost],
      [],
    ),
  'deletePost' : IDL.Func([PostId], [], []),
  'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCommentsForPost' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getPostById' : IDL.Func([PostId], [IDL.Opt(NewsPost)], ['query']),
  'getSavedPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'savePost' : IDL.Func([PostId], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'sharePost' : IDL.Func([PostId], [], []),
  'unsavePost' : IDL.Func([PostId], [], []),
  'unverifyUser' : IDL.Func([IDL.Principal], [], []),
  'verifyUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const Comment = IDL.Record({
    'id' : CommentId,
    'authorVerified' : IDL.Bool,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'postId' : PostId,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const NewsPost = IDL.Record({
    'id' : PostId,
    'authorVerified' : IDL.Bool,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'shares' : IDL.Nat,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
    'commentsCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'author' : IDL.Null,
    'contentCreator' : IDL.Null,
    'commonUser' : IDL.Null,
    'groupHead' : IDL.Null,
    'subscriber' : IDL.Null,
    'administrator' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'verified' : IDL.Bool,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : UserRole,
    'savedPosts' : IDL.Vec(PostId),
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfileInput = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [NewsPost],
        [],
      ),
    'deletePost' : IDL.Func([PostId], [], []),
    'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCommentsForPost' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getPostById' : IDL.Func([PostId], [IDL.Opt(NewsPost)], ['query']),
    'getSavedPosts' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'savePost' : IDL.Func([PostId], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'sharePost' : IDL.Func([PostId], [], []),
    'unsavePost' : IDL.Func([PostId], [], []),
    'unverifyUser' : IDL.Func([IDL.Principal], [], []),
    'verifyUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };