/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'authorVerified' : boolean,
  'text' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'postId' : PostId,
}
export type CommentId = bigint;
export type ExternalBlob = Uint8Array;
export interface NewsPost {
  'id' : PostId,
  'authorVerified' : boolean,
  'title' : string,
  'content' : string,
  'shares' : bigint,
  'authorName' : string,
  'author' : Principal,
  'likes' : bigint,
  'imageUrl' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'commentsCount' : bigint,
}
export type PostId = bigint;
export interface UserProfileInput {
  'username' : string,
  'displayName' : string,
  'profilePhotoUrl' : [] | [string],
}
export interface UserProfileSummary {
  'principal' : Principal,
  'verified' : boolean,
  'username' : string,
  'displayName' : string,
  'role' : UserRole,
  'registrationTimestamp' : bigint,
  'profilePhotoUrl' : [] | [string],
}
export interface UserProfileV2 {
  'verified' : boolean,
  'username' : string,
  'displayName' : string,
  'role' : UserRole,
  'savedPosts' : Array<PostId>,
  'registrationTimestamp' : bigint,
  'profilePhotoUrl' : [] | [string],
}
export type UserRole = { 'author' : null } |
  { 'contentCreator' : null } |
  { 'commonUser' : null } |
  { 'groupHead' : null } |
  { 'subscriber' : null } |
  { 'administrator' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[PostId, string], Comment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createPost' : ActorMethod<[string, string, [] | [ExternalBlob]], NewsPost>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'getAllComments' : ActorMethod<[], Array<Comment>>,
  'getAllPosts' : ActorMethod<[], Array<NewsPost>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfileSummary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileV2]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCommentsForPost' : ActorMethod<[PostId], Array<Comment>>,
  'getPostById' : ActorMethod<[PostId], [] | [NewsPost]>,
  'getSavedPosts' : ActorMethod<[], Array<NewsPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileV2]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'savePost' : ActorMethod<[PostId], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'sharePost' : ActorMethod<[PostId], undefined>,
  'unsavePost' : ActorMethod<[PostId], undefined>,
  'unverifyUser' : ActorMethod<[Principal], undefined>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'verifyUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];